#ifndef _hpstb_errorcode_h_
#define _hpstb_errorcode_h_

typedef enum
{
	HPSTB_OK = 0,
	HPSTB_FAIL = 1,
	HPSTB_TOO_MANY_CLIENTS = 2,
	HPSTB_NO_PERMISSION = 3,
	HPSTB_WAITING_FOR_NOTIFY = 4,//async notify for epg, pf, etc.
	HPSTB_NO_RESOURCE = 5,
	HPSTB_UNAUTHORIZED = 6,
	HPSTB_INVALID_PARAMS = 7,
	HPSTB_CLIENT_NOT_FOUND = 8,
	HPSTB_SERVER_ERROR = 9,
	HPSTB_MASTER_NOT_EXIST = 10,
	HPSTB_MASTER_ALREADY_EXIST = 11,
	HPSTB_NOT_BIND = 12,
	HPSTB_DISCONNECTING = 13,
	HPSTB_ACCESSTOKEN_ERROR = 14,
	HPSTB_NEED_PARENTRATING_PASSWD = 15,
	HPSTB_CONNECT_NEED_VERIFY = 16,
	HPSTB_CONNECT_VERIFY_FAIL = 17
}HPSTBErrCode;

#endif